# Generated by Django 2.1.7 on 2019-04-01 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='ch1ex3',
            field=models.BooleanField(default=False),
        ),
    ]
