# Generated by Django 2.1.7 on 2019-04-01 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_progress_ch1ex3'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='ch2ex1',
            field=models.BooleanField(default=False),
        ),
    ]
