# Generated by Django 2.1.7 on 2019-04-14 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_progress_ch2ex2'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='ch2ex3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='progress',
            name='ch2ex4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='progress',
            name='ch3ex1',
            field=models.BooleanField(default=False),
        ),
    ]
