# Generated by Django 2.1.7 on 2019-04-14 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190414_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='ch3ex2',
            field=models.BooleanField(default=False),
        ),
    ]
