# Generated by Django 2.1.7 on 2019-04-14 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_progress_ch3ex2'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='ch3ex3',
            field=models.BooleanField(default=False),
        ),
    ]
