# Generated by Django 2.1.7 on 2019-04-17 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_progress_ch3ex4'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='ch2ex1',
        ),
    ]
