# Generated by Django 2.1.7 on 2019-03-24 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz', models.CharField(default=False, max_length=10)),
                ('q1', models.CharField(default=False, max_length=30)),
                ('q2', models.CharField(default=False, max_length=30)),
                ('q3', models.CharField(default=False, max_length=30)),
                ('q4', models.CharField(default=False, max_length=30)),
                ('q5', models.CharField(default=False, max_length=30)),
                ('q6', models.CharField(default=False, max_length=30)),
                ('q7', models.CharField(default=False, max_length=30)),
                ('q8', models.CharField(default=False, max_length=30)),
                ('q9', models.CharField(default=False, max_length=30)),
                ('q10', models.CharField(default=False, max_length=30)),
            ],
        ),
    ]
