# Generated by Django 2.1.7 on 2019-03-24 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='q1',
            field=models.CharField(default=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='answers',
            name='q10',
            field=models.CharField(default=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='answers',
            name='q2',
            field=models.CharField(default=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='answers',
            name='q3',
            field=models.CharField(default=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='answers',
            name='q4',
            field=models.CharField(default=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='answers',
            name='q5',
            field=models.CharField(default=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='answers',
            name='q6',
            field=models.CharField(default=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='answers',
            name='q7',
            field=models.CharField(default=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='answers',
            name='q8',
            field=models.CharField(default=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='answers',
            name='q9',
            field=models.CharField(default=False, max_length=200),
        ),
    ]
